### ISSUE TITLE
Support customisation of graphql route (or use non pretty version)

### ISSUE THREAD

**Issue by homerjam** [wp-graphql/wp-graphiql#12]
I'm in an environment which means I'm having to use `/index.php?graphql` as my endpoint which means this plugin unfortunately doesn't work.

**Comment by jasonbahl** [comment]
@homerjam thanks for the issue. I can confirm that at the moment WPGraphiQL assumes the endpoint is at `/graphql`

I think it's reasonable for this plugin to support non-pretty permalinks as well. 

Thanks for reporting this. We'll try and get a fix in, but happy to accept PRs if you beat us to it 😄

**Comment by homerjam** [comment]
I'll try and take a look. Would you be happy to assume we can always use non pretty URLs?!

**Comment by jasonbahl** [comment]
ya. That works for me. I think it should be fine to just change this line to something that is more friendly for all environments?  🤔
