### ISSUE TITLE
Feature Request: GraphiQL Explorer

### ISSUE THREAD

**Issue by henrikwirth** [wp-graphql/wp-graphiql#14]
I am wondering if it would be easy to add the explorer that gatsby is using to this plugin. It makes it much easier to discover query options. 

Like here:
![Explorer](https://user-images.githubusercontent.com/476818/51567716-c00dfa00-1e4c-11e9-88f7-6d78b244d534.gif)

I am not sure what gatsby is using, but I found this: https://github.com/OneGraph/graphiql-explorer

**Comment by jasonbahl** [comment]
@henrikwirth yes! That's the one. I've had it on my mind to get it added. I'll try to get to it shortly, but happy for a PR if you beat me to it 😄

**Comment by henrikwirth** [comment]
This has been added in #16
