### ISSUE TITLE
wp-graphiql error "failed to open stream: HTTP request failed! HTTP/1.1 404"

### ISSUE THREAD

**Issue by TimurGumarov** [wp-graphql/wp-graphiql#2]
Hi! Got this error:
http://.../wp-content/plugins/wp-graphiql/assets/app/build/asset-manifest.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /.../wp-content/plugins/wp-graphiql-master/wp-graphiql.php on line 60

**Comment by TimurGumarov** [comment]
Can anyone help me with this?

**Comment by jasonbahl** [comment]
@timurgumarov my guess is maybe a file permission issue? We have the plugin active on a few sites with no issues.

**Comment by TimurGumarov** [comment]
@jasonbahl  I'm just downloaded the plugin, uploaded to server and didn't set any permissions.
May be i must show here something that can help resolve this problem?

P.S.: Sorry for my English if it's not good.

**Comment by jasonbahl** [comment]
@TimurGumarov possibly something with your upload to the server caused the file to not be readable. I haven't experienced the issue your saying so I'm just taking guesses at this point. What are the permissions on that manifest.json file?

**Comment by jasonbahl** [comment]
@TimurGumarov maybe see if any of the suggestions here help. https://stackoverflow.com/questions/36577020/php-failed-to-open-stream-no-such-file-or-directory

**Comment by TimurGumarov** [comment]
@jasonbahl Oh. Sorry for my inattention.
I see, that there is no **build** folder in **app** folder but request needs json file in it.
`http://.../wp-content/plugins/wp-graphiql/assets/app/build/asset-manifest.json`

**Comment by jasonbahl** [comment]
Ah. Hmm. I can push up a change that includes the build folder in a bit. Must've been .gitignored as typically it would be part of a build process, but in a WP plugin there is no build process so it should be included in the version es assets

**Comment by jasonbahl** [comment]
@TimurGumarov sorry for the delay, but this issue should now be resolved and the `/build` directory is now included in the plugin files when you download or clone without any extra build step.

**Comment by TimurGumarov** [comment]
@jasonbahl Thank you Jason!

**Comment by irelandpaul** [comment]
I had this same problem but possibly a different cause. 

I found that you have to ensure your plugin direction is called 'wp-graphiql'. If you just upload the zip, it'll be called 'wp-graphiql-master' and it will not recognize the build directory because it points to: wp-graphiql/assets/app/build/asset-manifest.json

@jasonbahl Thanks for your great work on this!

**Comment by TimurGumarov** [comment]
@irelandpaul Hi!
Yeah, I saw this too.
