### ISSUE TITLE
composer support

### ISSUE THREAD

**Issue by richardsweeney** [wp-graphql/wp-graphiql#20]
Hey! Such a great and super-useful plugin, huge thanks for this.

Is there any chance you'd consider adding composer support for this repo?

**Comment by ryankellypercussion** [comment]
Add
```json
{
  "type": "vcs",
  "url": "https://github.com/wp-graphql/wp-graphiql"
}
```

to your repositories to require it.

**Comment by esamattis** [comment]
I think this just needs to be published to the packagist like other wp-graphql family plugins

**Comment by matepaiva** [comment]
It would be very practical if this package was published to packagist :)

**Comment by jasonbahl** [comment]
@richardsweeney @ryankellypercussion @esamattis @matepaiva sorry for the delay. Got this up on packagist. 

https://packagist.org/packages/wp-graphql/wp-graphiql

**Comment by matepaiva** [comment]
Thanks! The plugins work like a charm, they are very helpful. Thank you very much!
