### ISSUE TITLE
Plugin installation

### ISSUE THREAD

**Issue by clairemariko** [wp-graphql/wp-graphiql#3]
When activated I get this warning in the GraphiQL interface
`file_get_contents ....../wp-content/plugins/wp-graphiql/assets/app/build/asset-manifest.json): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found`

This is the call stack

> do_action('admin_enqueue_scripts')
wp-admin/admin-header.php:97
WPGraphiQL->enqueue_react_app()
wp-includes/class-wp-hook.php:286
WPGraphiQL->get_app_stylesheet()
wp-content/plugins/wp-graphiql-master/wp-graphiql.php:109
WPGraphiQL->get_app_manifest()
wp-content/plugins/wp-graphiql-master/wp-graphiql.php:71
file_get_contents()
wp-content/plugins/wp-graphiql-master/wp-graphiql.php:60

> 

Any ideas? This is my first wordpress with GraphiQL application so apologies if the solution is obvious.

**Comment by jasonbahl** [comment]
@clairemariko try renaming the directory of the plugin to `wp-graphiql` instead of `wp-graphiql-master`

**Comment by jasonbahl** [comment]
@clairemariko I just pushed an update that should make the plugin work fine even if the directory is named something other than `wp-graphiql`

**Comment by clairemariko** [comment]
@jasonbahl thank you very much for your help and fast response!
It worked perfectly renaming the plug :)
