### ISSUE TITLE
Variables are invalid JSON:

### ISSUE THREAD

**Issue by sathishkumar-me** [wp-graphql/wp-graphiql#31]
![image](https://user-images.githubusercontent.com/71722874/97351797-41af7900-18b8-11eb-982b-c578348cf010.png)

**Comment by jasonbahl** [comment]
What version of WPGraphQL are you on? This repo is deprecated. GraphiQL is built into WPGraphQL v0.13+ now.

**Comment by sathishkumar-me** [comment]
![image](https://user-images.githubusercontent.com/71722874/97352938-5f311280-18b9-11eb-8246-ea968210925b.png)

**Comment by sathishkumar-me** [comment]
And a blank "GraphQL Settings" page

**Comment by jasonbahl** [comment]
Ok, so you don't need this repo `wp-graphiql` also active. 

Do you have WPGraphiQL also active?

**Comment by sathishkumar-me** [comment]
Deleted WPGraphiQL plugin . Still facing the same problem.

**Comment by jasonbahl** [comment]
Can you paste this query and try again? 

```
query GET_POSTS {
  posts {
    nodes {
      id
      title
    }
  }
}
```

**Comment by jasonbahl** [comment]
It seems like some sort of formatting error based on the RED syntax highlighting

**Comment by sathishkumar-me** [comment]
![image](https://user-images.githubusercontent.com/71722874/97354023-ce5b3680-18ba-11eb-9d83-4b895c2a27d0.png)

**Comment by sathishkumar-me** [comment]
![image](https://user-images.githubusercontent.com/71722874/97354111-ecc13200-18ba-11eb-8cd6-22b391e4c957.png)

**Comment by jasonbahl** [comment]
Oh, you're putting the query in the "variables" window, not the "Query" window. 

Minimize the "variables" and put the query in the window above

**Comment by sathishkumar-me** [comment]
Where is Query window. Iam not able to type in the right side.

**Comment by sathishkumar-me** [comment]
![image](https://user-images.githubusercontent.com/71722874/97357151-55121280-18bf-11eb-8c75-dfd6cfb733dc.png)

**Comment by jasonbahl** [comment]
@sathishkumar-me see the screen recording below:

![graphiql-variables-window](https://user-images.githubusercontent.com/1260765/97893223-3a400380-1cee-11eb-90b6-d9995555f601.gif)
