### ISSUE TITLE
Wrong location url

### ISSUE THREAD

**Issue by gadzet** [wp-graphql/wp-graphiql#7]
It's sending requests to localhost/graphql where my site is localhost/sitename/grapqhl, changing it in App js or in bundle didn't fix the issue.

**Comment by jasonbahl** [comment]
Thanks for reporting. I’ll see what I can find out to fix it.

**Comment by jasonbahl** [comment]
@gadzet does your GraphQL endpoint work in general, just not from the wpgraphiql plugin?

**Comment by gadzet** [comment]
@jasonbahl works from my chrome plugin, the error is inn the App.js 
`  return fetch(window.location.origin + '/graphql', {
`
because origin is only taking base url without /sitename so it should get it from database or at least be configurable.

**Comment by jasonbahl** [comment]
@gadzet ok sweet. Thanks for the extra details. I know how to fix this. I’ll try and get a PR in today.

**Comment by jasonbahl** [comment]
@gadzet pushed up a fix. can you confirm it's working now?

**Comment by gadzet** [comment]
@jasonbahl works like a charm. thanks
